FROM mysql:8.0
ENV MYSQL_ROOT_PASSWORD=ExpenseApp1
RUN groupadd expense && \
    useradd -g expense  expense && \
    chown -R expense:expense /var/lib/mysql /var/run/mysqld /docker-entrypoint-initdb.d
USER expense
ADD scripts/*.sql /docker-entrypoint-initdb.d/
EXPOSE 3306